Parameters:
  BucketName:
    Description: Name of S3 bucket
    Type: String
    ConstraintDescription: must be a valid S3 bucket name.

Resources:
  NexusBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Name
          Value: !Ref BucketName

  NexusBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket:
        Ref: 'NexusBucket'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPublicReadAccess
            Effect: Allow
            Principal: '*'
            Resource: !Sub 'arn:aws:s3:::${NexusBucket}/*'
            Action:
              - 's3:GetObject'
    DependsOn:
      - NexusBucket
